const wordPuzzleWords = {
  Apple: "A sweet fruit that grows on trees.",
  Chair: "A piece of furniture to sit on.",
  Ocean: "A large body of saltwater.",
  School: "A place where students go to learn.",
  Tiger: "A large wild cat with orange fur and black stripes.",
  Bridge: "A structure built to cross over water or roads.",
  Window: "An opening in a wall that lets light in.",
  Balloon: "A thin rubber bag filled with air or gas.",
  Garden: "A place where plants and flowers are grown.",
  Friend: "A person you like and enjoy spending time with.",
  River: "A natural flowing stream of water.",
  Bottle: "A container for liquids, usually with a narrow neck.",
  Guitar: "A musical instrument with strings.",
  Doctor: "A person who treats sick people.",
  Elephant: "A large, gray animal with a trunk.",
  Library: "A place where you can borrow and read books.",
  Mountain: "A large natural elevation of the earth's surface.",
  Breakfast: "The first meal of the day.",
  Rainbow: "A colorful arc in the sky after rain.",
  Laptop: "A small portable computer.",
  Sunflower: "A tall plant with a large yellow flower.",
  Teacher: "A person who helps students learn.",
  Football: "A popular sport played with a round ball.",
  Bedroom: "A room where people sleep.",
  Chocolate: "A sweet treat made from cocoa.",
  Hospital: "A place where sick people are treated.",
  Rocket: "A vehicle designed to travel in space.",
  Festival: "A special event or celebration.",
  Holiday: "A day off from work or school for celebration.",
  Island: "A piece of land surrounded by water.",
  Market: "A place where people buy and sell things.",
  Mirror: "A reflective surface to see yourself.",
  Pencil: "A tool used for writing or drawing.",
  Subway: "An underground train system.",
  Clock: "A device that shows time.",
  Desert: "A hot, dry, and sandy place.",
  Village: "A small group of houses in the countryside.",
  Bicycle: "A two-wheeled vehicle powered by pedaling.",
  Raincoat: "A waterproof coat to wear in the rain.",
  Firefighter: "A person who puts out fires.",
  Compass: "A tool used for finding directions.",
  Airport: "A place where airplanes take off and land.",
  Glasses: "A tool worn to see better.",
  Curtain: "A piece of fabric that covers windows.",
  Refrigerator: "A device to keep food cold.",
  Notebook: "A book for writing notes.",
  Elevator: "A platform that moves people up or down floors.",
  Zoo: "A place where animals are kept for the public to see.",
  Carpet: "A thick floor covering.",
  Jungle: "A dense forest in a tropical area.",
  Fence: "A barrier made of wood or metal around an area.",
  Fireplace: "A place in a house to light a fire for warmth.",
  Garage: "A place to park vehicles.",
  Bakery: "A place where bread and cakes are made and sold.",
  Lighthouse: "A tower with a light to guide ships.",
  Castle: "A large, strong building for royalty.",
  Playground: "A place for children to play.",
  Mailbox: "A box for receiving letters.",
  Train: "A vehicle that runs on tracks.",
  Piano: "A large musical instrument with keys.",
  Helmet: "A protective headgear.",
  Cinema: "A place where people watch movies.",
  Swimming: "The act of moving through water.",
  Engineer: "A person who designs and builds things.",
  Police: "A group of people who keep order and safety.",
  Hotel: "A place where travelers can stay.",
  Kitchen: "A room where food is cooked.",
  Submarine: "A vehicle that travels underwater.",
  Star: "A bright point in the sky at night.",
  Forest: "A large area covered with trees.",
  Planet: "A large celestial body in space.",
  Astronaut: "A person who travels in space.",
  Microscope: "A tool to see very small objects.",
  Tent: "A portable shelter made of cloth.",
  Volcano: "A mountain that can erupt with lava.",
};

function getRandomWord(list) {
  const keys = Object.keys(list);
  const randomKey = keys[Math.floor(Math.random() * keys.length)];
  return { word: randomKey, definition: list[randomKey] };
}

const verbSentences = {
  "do not go": "We _____ (not go) to school on Sundays.",
  plays: "She _____ (play) the piano every day.",
  "do not eat": "They _____ (not eat) meat.",
  watches: "He _____ (watch) TV every night.",
  "do not like": "I _____ (not like) spicy food.",
  cries: "The baby _____ (cry) a lot at night.",
  need: "You _____ (need) a ticket to enter.",
  "does not drink": "She _____ (not drink) coffee in the morning.",
  writes: "Tom _____ (write) a letter every week.",
  "do not swim": "We _____ (not swim) in cold water.",
  studies: "He _____ (study) hard for his exams.",
  "do not drive": "I _____ (not drive) a car.",
  reads: "She _____ (read) a book before bed.",
  "do not visit": "They _____ (not visit) their grandparents often.",
  call: "You _____ (call) your mom every day.",
  "does not do": "He _____ (not do) his homework on time.",
  watch: "We _____ (watch) movies on weekends.",
  "does not play": "She _____ (not play) video games.",
  rises: "The sun _____ (rise) in the east.",
  "do not have": "I _____ (not have) any pets.",
  travel: "They _____ (travel) during holidays.",
  "does not work": "She _____ (not work) on Sundays.",
  speak: "You _____ (speak) very fast.",
  "does not sleep": "He _____ (not sleep) early.",
  clean: "We _____ (clean) the house every Saturday.",
  "does not like": "John _____ (not like) horror movies.",
  sleeps: "The cat _____ (sleep) on the couch.",
  "do not go": "I _____ (not go) to the gym often.",
  play: "They _____ (play) soccer after school.",
  writes: "She _____ (write) in her diary every night.",
  "does not eat": "He _____ (not eat) junk food.",
  visit: "We _____ (visit) our grandma every Sunday.",
  "does not drive": "She _____ (not drive) to work.",
  study: "They _____ (study) in the library.",
  "do not watch": "I _____ (not watch) TV at night.",
  need: "You _____ (need) to finish your homework.",
  "does not call": "He _____ (not call) his friends often.",
  eat: "We _____ (eat) dinner at 7 PM.",
  "does not exercise": "She _____ (not exercise) regularly.",
  "does not wash": "Tom _____ (not wash) his car.",
  read: "I _____ (read) the newspaper every morning.",
  "do not go": "They _____ (not go) to bed early.",
  likes: "She _____ (like) chocolate ice cream.",
  "do not travel": "We _____ (not travel) often.",
  "does not buy": "He _____ (not buy) expensive clothes.",
  sleeps: "The baby _____ (sleep) all day.",
};

function generateID() {
  return (Date.now() % 1000000).toString().padStart(6, "0");
}
module.exports = { getRandomWord, wordPuzzleWords, verbSentences, generateID };
